"""Add video_generation_requests table

Revision ID: 272fef9a7d33
Revises: 0461d6bd6272
Create Date: 2025-08-29 00:10:09.461738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272fef9a7d33'
down_revision: Union[str, Sequence[str], None] = '0461d6bd6272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_generation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('runwayml_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generation_requests_id'), 'video_generation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_video_generation_requests_runwayml_task_id'), 'video_generation_requests', ['runwayml_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_generation_requests_runwayml_task_id'), table_name='video_generation_requests')
    op.drop_index(op.f('ix_video_generation_requests_id'), table_name='video_generation_requests')
    op.drop_table('video_generation_requests')
    # ### end Alembic commands ###
